import type { Startup } from '@/components/StartupCard'

export const STARTUPS: Startup[] = [
  {
    id: 1,
    name: '리프레임 AI',
    industry: 'AI · B2B SaaS',
    founded: 2021,
    score: 94,
    stage: 'Series A',
    growth: '+182%',
    funding: '2024.04',
    tag: '강한 매수',
    summary: '제조 현장의 비정형 데이터를 실시간으로 구조화하는 산업 AI 플랫폼',
    model: '구독형 SaaS와 API 사용량 기반 과금으로 반복 매출을 확보합니다.',
    market: '국내 스마트팩토리 전환 수요와 함께 아시아 제조 AI 시장으로 확장 가능성이 높습니다.',
    growth_text: '최근 12개월 ARR 182% 성장, 고객 유지율 118%를 기록했습니다.',
    competition: '도메인 특화 데이터셋과 현장 연동 레퍼런스가 진입장벽으로 작용합니다.',
    valuation: '150~200억원',
    fair: '175억원',
    basis: 'ARR 18억원에 유사 상장사 매출배수 9.7배를 적용하고, 성장률 프리미엄을 반영했습니다.',
    confidence: 86,
    history: ['2024.04 · Pre-A · 32억원', '2022.11 · Seed · 8억원'],
  },
  {
    id: 2,
    name: '메디플로우',
    industry: '헬스케어',
    founded: 2020,
    score: 91,
    stage: 'Series A',
    growth: '+146%',
    funding: '2024.01',
    tag: '매수',
    summary: '병원 운영 데이터를 기반으로 진료 대기와 자원 배치를 최적화하는 솔루션',
    model: '병상 수 기준의 연간 라이선스와 도입 컨설팅을 결합한 모델입니다.',
    market: '상급종합병원 중심의 검증 후 중소병원으로 확장할 수 있는 시장입니다.',
    growth_text: '유료 병원 수가 전년 대비 2.3배 증가했습니다.',
    competition: 'EMR 연동 노하우와 의료기관별 워크플로우 데이터가 차별점입니다.',
    valuation: '120~165억원',
    fair: '142억원',
    basis: '반복 매출 비중 78%와 동종 헬스케어 SaaS 거래사례를 비교했습니다.',
    confidence: 82,
    history: ['2024.01 · Series A · 45억원', '2021.09 · Seed · 6억원'],
  },
  {
    id: 3,
    name: '그린루프',
    industry: '기후테크 · 순환경제',
    founded: 2019,
    score: 88,
    stage: 'Pre-Seed',
    growth: '+121%',
    funding: '2023.10',
    tag: '매수',
    summary: '폐플라스틱 회수부터 재생 원료 거래까지 연결하는 순환자원 운영 플랫폼',
    model: '거래 수수료와 원료 품질 분석 서비스 매출을 병행합니다.',
    market: 'ESG 공시 확대와 재생 원료 의무 사용 비율 상승이 수요를 뒷받침합니다.',
    growth_text: '거래 물량과 매출이 동반 성장하며 손익분기점에 근접했습니다.',
    competition: '수거 파트너 네트워크와 품질 데이터 축적이 핵심 경쟁력입니다.',
    valuation: '95~135억원',
    fair: '115억원',
    basis: '거래액 성장률, 수수료율, 유사 자원순환 기업의 EV/Sales를 반영했습니다.',
    confidence: 78,
    history: ['2023.10 · Pre-Seed · 20억원', '2020.12 · Seed · 4억원'],
  },
  {
    id: 4,
    name: '핀브릿지',
    industry: '핀테크 · 인프라',
    founded: 2022,
    score: 86,
    stage: 'Seed',
    growth: '+208%',
    funding: '2024.06',
    tag: '관심',
    summary: '중소사업자를 위한 정산·현금흐름 자동화 금융 인프라',
    model: '월 구독료와 연동 거래 기반 수수료로 수익을 만듭니다.',
    market: '소상공인 금융 운영 자동화의 초기 시장을 선점하고 있습니다.',
    growth_text: '월간 활성 사업자가 6개월간 3배 증가했습니다.',
    competition: '회계·결제 데이터를 단일 화면으로 연결한 경험이 강점입니다.',
    valuation: '70~100억원',
    fair: '85억원',
    basis: '초기 단계 SaaS 거래사례와 활성 고객 성장률을 반영했습니다.',
    confidence: 73,
    history: ['2024.06 · Seed · 12억원'],
  },
  {
    id: 5,
    name: '모빌리티온',
    industry: '로보틱스 · 물류',
    founded: 2020,
    score: 84,
    stage: 'Series B',
    growth: '+97%',
    funding: '2023.12',
    tag: '관심',
    summary: '도심 라스트마일 배송을 위한 수요 예측 및 배차 최적화 엔진',
    model: '배송 건당 사용료와 엔터프라이즈 라이선스를 제공합니다.',
    market: '퀵커머스와 당일배송 확대로 최적화 솔루션 수요가 지속됩니다.',
    growth_text: '고객사당 배송 처리량이 74% 증가했습니다.',
    competition: '배송 데이터 기반 예측 정확도와 빠른 도입 속도가 차별점입니다.',
    valuation: '110~150억원',
    fair: '128억원',
    basis: '매출 성장률과 물류 SaaS 유사기업의 매출배수를 교차 적용했습니다.',
    confidence: 76,
    history: ['2023.12 · Series B · 38억원', '2021.07 · Seed · 7억원'],
  },
]
